export const SETCOUNTER = "SETCOUNTER";
export const SETUSERDETAILS = "SETUSERDETAILS";
export const SETLOADER = "SETLOADER";
export const SETNAVBARHEADING = "SETNAVBARHEADING";
export const SETHOSPITALSELECTED = "SETHOSPITALSELECTED";
export const SHAREDLOADER = "SHAREDLOADER";
export const SETWALLETBALANCE = "SETWALLETBALANCE";
